apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.config.secrets }}
  {{ $key | upper }}: {{ $val | b64enc }}
  {{- end }}